 
tasks:
  -  command: npm install   &&
              node index.js  &&
              gp preview https://hpssjellis.github.io/gitpod-portenta-websocket/public/index.html  --external   
ports:
  - port: 8080    
    visibility: public
    onOpen: open-preview
